apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-static-1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-05db4f7a661a60069
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: efs-static-1
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: app-1
  labels:
    demo: efs-static-1
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: nginx-data
      mountPath: /usr/share/nginx/html
  volumes:
  - name: nginx-data
    persistentVolumeClaim:
      claimName: efs-static-1
---
apiVersion: v1
kind: Service
metadata:
  name: efs-static-1
spec:
  type: LoadBalancer
  selector:
    demo: efs-static-1
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #container-port